### PR TITLE
Fix multifile yaml files

### LINKED ISSUE #95: v0.13 - no warnings or fails with multi-file yamls
When upgrading from 0.11 to 0.13, conftest went silent. No warnings or failed tests.

```
# previously

$ brew switch conftest 0.11.0
$ conftest test deployment.yaml
FAIL - prometheus-adapter is running as root

# now

$ brew switch conftest 0.13.0
$ conftest test deployment.yaml

# silent...
```

I expected at least some output, not just silently passing all tests. 

```
$ conftest --version
Version: 0.13.0
Commit: 8340065
Date: 2019-09-27T22:40:00Z
```

### PR DESCRIPTION
**Pull request by jpreese**
I didn't want to go too crazy as it's intended to be a bug fix, but after digging through the source some I see some opportunities for refactoring that I'd like to follow up on. I'll add an issue for that.

**This PR**
- Resolves #95 
- Implements #85 (with additional updates)

- Combines the `test_test` package into the `test` package
*reasoning: I find it much easier to deal with tests when the code under test and the tests themselves live in the same package. It lets you dodge unnecessary mocking when dealing with public APIs and just execute tests against the core logic*

- Adds a new test, `TestMultifileYaml`. Showcases that multifiles did not work before this PR, and now they do.

- Adds a new test, `TestDockerfile`. Ran into some problems when dealing with marshalling and slices (e.g. multi yamls and dockerfile commands). The acceptance test highlighted this problem, so the added test alerts us sooner if behavior changes.

### CODE REVIEW

File: pkg/commands/test/test_test.go [hunk 1]
```diff
@@ -173,11 +171,84 @@ func TestFailQuery(t *testing.T) {
...
+COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
+COPY ${DEPENDENCY}/META-INF /app/META-INF
+COPY ${DEPENDENCY}/BOOT-INF/classes /app
+
+ENTRYPOINT ["java","-cp","app:app/lib/*","hello.Application"]`
+
+	parser := docker.Parser{}
+
+	var jsonConfig interface{}
+	parser.Unmarshal([]byte(config), &jsonConfig)
```
Comment (golangcibot) [inline pkg/commands/test/test_test.go]: Error return value of `parser.Unmarshal` is not checked (from `errcheck`)

File: pkg/commands/test/test.go [hunk 2]
```diff
@@ -229,41 +244,64 @@ func makeQuery(rule string) string {
...
+}
+
+func runRules(ctx context.Context, input interface{}, regex *regexp.Regexp, compiler *ast.Compiler) ([]error, error) {
+	var totalErrors []error
+	var errors []error
+	var err error
+
+	rules := getRules(ctx, regex, compiler)
+	for _, rule := range rules {
+		_, multiple := input.([]interface{})
```
Comment (boranx) [inline pkg/commands/test/test.go]: what about changing this with type checking switch-case like:

		switch input.(type) {
		case []interface{}:
			errors, err = runMultipleQueries(ctx, makeQuery(rule), input, compiler)
		case interface{}:
			errors, err = runQuery(ctx, makeQuery(rule), input, compiler)
		}

Comment (jpreese) [reply pkg/commands/test/test.go]: I think this makes sense. All set!

**Comment by garethr** [comment]
Thanks, appreciated. Merging and I'll get a new release out shortly.
